version: '3.8'
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres_container_cds
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cds
      POSTGRES_PASSWORD: cds
      POSTGRES_DB: cds
    volumes:
      - postgres_data_cds:/var/lib/postgresql/data
volumes:
  postgres_data_cds: